databases:
  - name: budgetapp
    databaseName: budgetapp_qh3v
    user: budgetapp_qh3v_user

services:
  - type: web
    name: budgetapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zuwairanajma
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false